{
  "language": "java",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "jdk": [
    "openjdk8",
    "oraclejdk8"
  ],
  "branches": {
    "only": [
      "master",
      "development"
    ]
  },
  "before_script": [
    "cd project",
    "ls -la"
  ],
  "script": [
    "mvn clean package"
  ],
  "after_success": [
    "echo Process terminated successfully"
  ]
}